services:

    traefik:
        image: containous/traefik:pr-433
        command: --web --docker --docker.domain=localhost --logLevel=DEBUG
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "127.0.0.1:8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/etc/traefik/traefik.toml
            - ./acme:/acme

    huitparfait-front:
        image: huitparfait/huitparfait-front
        restart: always
        labels:
            - "traefik.backend=huitparfait-front"
            - "traefik.protocol=http"
            - "traefik.port=80"
            - "traefik.frontend.rule=Host:localhost"

    huitparfait-auth:
        build: ./huitparfait-auth
        image: huitparfait/huitparfait-auth
        restart: always
        env_file:
            - .env
            - .env.local
        volumes:
            - ./keys:/jwt-keys
        environment:
            NODE_ENV: production
            JWT_PUBLIC_KEY_PATH: /jwt-keys/jwt-public.pem
            JWT_PRIVATE_KEY_PATH: /jwt-keys/jwt-private.pem
            PROXY_API_URL: http://huitparfait-api:3000
        labels:
            - "traefik.backend=huitparfait-auth"
            - "traefik.protocol=http"
            - "traefik.port=3000"
            - "traefik.frontend.rule=Host:localhost;PathPrefix:/api,/auth"

    huitparfait-api:
        build: ./huitparfait-api
        image: huitparfait/huitparfait-api
        restart: always
        env_file:
            - .env
            - .env.local
        volumes:
            - ./keys:/jwt-keys
        environment:
            NODE_ENV: production
            JWT_PUBLIC_KEY_PATH: /jwt-keys/jwt-public.pem
            API_SERVER_PORT: 3000
