defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[acme]
# À configurer pour ton domaine en prod (pas huitparfait.fr)
email = "admin@example.com"
storageFile = "/acme/acme.json"
entryPoint = "https"
[[acme.domains]]
  main = "pronos.example.com"
